### ISSUE TITLE
Plans for better description of decays

### ISSUE THREAD

**Issue by jiangyi15** [jiangyi15/tf-pwa#152]
There are many ways can be implemeted to simplify the current description of decays. 

- [x] Replace rules : support replace decay node with particles name when it is list.
use 
```yaml
decay:
    A: 
    - [ R, B]
    R: [ C, D]
particle:
     R: [R1, R2]
```
to produce
```yaml
decay:
    A: 
    - [ R1, B ]
    - [ R2, B ]
    R1: [ C, D ]
    R2: [ C, D ]
```
- [x] Properities from `Resonaces.yml` and override in `config.yml`.
use 
```yaml
# in Resonances.yml
R1:
    J: 1
    P: +1
    mass: 1.0
    width: 0.05
```
```yaml
# in config.yml
particle:
   R1:  
      mass:  1.1
```
to produce
```yaml
# in config.yml
particle:
  R1:
      J: 1
      P: +1
      mass: 1.1
      width: 0.05
```
- [ ] Support multiply particles of top nodes. (A -> B C D, B -> E F G)
  - aligned in each parts to avoid much combination. 
  - combine the amplitude of  them like a decay chain.
- [ ] Better way to deal with identical particles.
